apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: caralegal-dev
  namespace: argocd
spec:
  description: Caralegal dev environment
  sourceRepos:
    - 'https://github.com/markof88/gitops-demo'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: demo
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: PersistentVolumeClaim
    - group: batch
      kind: Job
    - group: bitnami.com
      kind: SealedSecret
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: NetworkPolicy
