---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgBlL0wwg0nGU7cnUf4HoSnZV5Ax4Je/0hKDaOIhUf2Z7+JM9YEUTb6E2GTHKw0LltsEHBRlTOplUPQ2o+xcs/tHzJBwOpWBVbUjfXMR24h5RKOCgWcN8TkOlHzBVlcjK9KyFAhKHvmF6wIcHecu4p5HhNszikfDJgXnZnFGKnvSr31vOc4iZErn3ldPUVweX9+spPrMV/JNTTXju8Gn8Plcm+6P+D+W8qrNlLMdXlB2lsyWmciqpZFjgM3EfCEnoo1ZAkAGKVUxAv7/Quj+jf3iz5NgQ09ZGASln8YwX6OHQUekjTWOeKHQ356OPSKxscpiwGiFSMOoLpk/X3setPKx6lmJQX1b4pxq3dwl9CyNkpZs7BnJct4XiAQW3CB8pKRPJhtuMj7oJUirzHz6+V3A5vLbPgk6d/IzA8+nVExd0bqBWxYivGRnoL1LdNdL6M53g3uybRWpiiuoOsnQBd7Lih7WA7B4FdoNMo+PnXR9z1qNazJEHtsd8hbye7ZvyMInL9bV0xW4b3SHswURse7CCm4LfRE86mHQ9q4hJdiw0pcTJDUmoCK31hCvdNQz6I1J+G+C/Qc1PjqsvQShvkLJsu5voQ4B4wQYr0KASOKDh7svTC1+Rbwi9eGMQRpTSQoBY4rmxMnKQn+Mdzv2onIVLRySFpve1LmrNKPvqwaJ8ylccGDdQBtBwN9Y4E4VbmIM3LwLikBUuOkPh7tEQnrkd0i31NY=
  template:
    metadata:
      name: demo-secret
      namespace: demo
