---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgCgzAgMUE5xyc9SE6RcIlwmeLy1aerefHRbbsRGDryCDOWhYrPW6C4De3225n5fRKAEh+pO1bmrSVzpKyVPc6NF4NpaoUMl5M5qujOGVJMfHBXzHJaw/3CPiWxSXosNxRpm1ui56EN5bjpw1AOuulXhXBNictI7NmkSQQTWY2SjYh7ee1I99GpzZxsSPpltd69XD2Efk/NgM2lPtwBM2DqHE8FKo44+f6LgQwU+Xp4GRTmVmL16wevONDSMBGA+zegjZ5YQkQN1DXeyNjEXk+EWDECHVhj9zLpybL1xYAbkrqlz2Y1P0hv4CwN5xnmJlxaEYQn9ZArqeh+oPoCMVPYzB8oLOWU5s1GSv3KJAIl5Kh+0edMAIDIR3LN7qY/mKJcBOz01CBMwhc0xV7BTB2nYNuNVewyYvD9H1FrFWG8gP5f6lonnkVBoSkaDkgB1wpcMmhqQdxFenXlDABlrZnUGDgEBvRgyfjkR2ROT4XZSyNqbw5Qj4n3yThGApZlyanMPserDWvIDYEblye8eVS29yPUg97O242bJc/jqO87FBGToVtxFLEt5yMMkNbwsua769lSACxWH93P7VFF7TzvwEBppZP4/Nactz/5JkuHHs0eQGZ8FWF88yPmmoTW61lYDq5a/5Ddp52ABNEo53N4ug37TwhpNn9doUmfmiTq9neURw5wsHnc+N+5yE3vM6yKFaKqGKtrRu+HB1TEf90cQQC9MJw==
  template:
    metadata:
      name: demo-secret
      namespace: demo
