apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: caralegal-prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  source:
    repoURL: 'https://github.com/markof88/gitops-demo'
    targetRevision: HEAD
    path: apps/demo-app/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
