---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  encryptedData:
    password: AgCD7eCuA0HHeYOh292KwKTWg3MiHjkFrPVaeBe58PPCTFjtlW+TJsLRHAYvP1aSGP+BSW+BAj66+/U96VJIcVE50RIodUsNfPZI0Ht2g8AOwgFb+7FTzAXgLGs2Pw+NVix+zZw1CMTmXONLMbULiXRuPDVMt+sPy/S1eNWjl/r1y/M+Xbm5Xvrd0wtj8QgvHAHtnOcyMkGLuexzkzDEZ7PF5EW79ni8TSjxK+WMqKOfzSenUc+EdPhSVZ+Ew9LNSKyj+45WZSGvrszT2/YbWrbVeh2FsWjdAQateOJ9ENOvaqIKtJeJUwvnsdJCBWw9wEPP9z0YzNlzaTX9Xul8k7EYHRFnrYPgjvjuDl5OBO+YL5cW0K/TPDOF6blCZ3e9TMGs8vDgyysJPxXxS01qG83k3cmay8j1Cj5hOLbPABkAJDIrUZmb7vfILlUnIchsTbiVTn+EQJ/sIwxugoVsE8ZYmmukMEUfRsLTgMsVXyOr/WhZHLrjZRINcTnD/ntoG3P7h5ysHrKmAtvX+CJXIAs2pC7m32aYR+/26esJ5XaSxzu/Tt0QKdWJ9w30FHsTPTLJevV83Ke9dUob5wIXLMKXxqLP4aKJ5TZhFdsfurjIgoA71F+Qq16Z9wGRanbCrWsk8vl2kl7sen6sYOleq5sUxddKZMp8fYwcgxymznCnyP/9PZx3eaxZf28SgL1iW0Q7B7usQ+TL/YmtWLMN0K5V
    username: AgAhIAfw6iipAKPT0FbuB7RXnnon2mnL9NnJKiOQX2t1TFZViDwpczotuXzIUaXW/LJQSSeQIQwrNwOAaJyu97TE5bD5UljfDeB02c78sWXax5ZKzGqPLIK8If+Ie/OqwWXzJtC3w5A6WA8QlOO13g7zgHVb7hGIP2s8xjsxEib9mMWaCJILdxVklYePnPfKonTP0qILZKwUOa01T9E7JmnUP6mz0MEjA/QMv1b6lmvk7Hmz0ZmSdTxyEz6ZjIxzdMdEjCIP8nMRjFyryX44RTtXIEzdkxV2c9/cSxHs4GCIO0J6VBlqRKgyq9nPrvaoUO0RJrqm+2XEMESjP7ehzDdPXS6OABWkpHdo//wvnQXQ8rNK+epLjd8Qtyl8C1yHQYFF03mVJB/S6mUZQNElsw3agNuBvXbc86Akn8Crjp9wyq3Y1ift0NJu5THRsFcYlMVoChRlItCATHM/o5W5xvl7W0kVEqyl7wvEs+66WT5F8J8rZ7wYcIEfA0BHIZQxpZZ3MprYn+CpuCXOMd8yR/xe26V+jY0txeRTIKTdCmeuxy/agoTKm8gztXloM2DfRwnKfeLPuMRQdTP4BZNOJiXuCMSJ0QLCAMBT4Dc2ezxdt/byRUjyDBefSKM3bOb1AjjiIMQUw8E7ubhgwJnTat0r/M743kfI8frpC1qPhyzCpw3YEK8CN+DEKntAL68oQPBTh4MAXxGQkg==
  template:
    metadata:
      name: app-db-secret
      namespace: demo
