---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgBC378cByBX+iy7FveC78RIa9CDhtPrKOCH/n1gySb7RiWJATRiRW2iozUtX8rrBNxU6X+kc4vAGoOMAANlTrCS6Y3i7E7woU0abSbODvlS37/40sq8NQCjxrKUsZQco6+sGTklmOebDcEnkHvOKbxr4MmZ5TdrjP3We87eyiRq6M+9iOVd9+wreYN5tA3NkvZZb+ruhWuE7qxr+LEA3SdcdRF3EZTkA031inyRwQfDM+ob9Ur7+ZDNj2Ni4QwI9uOx60LerirsC8F2DHFGNaQjuJM1hyRjrW1oc5RKiLQJZL5i7oVKD5cyyYYW9RbyqiSjLfB6D9FEtd6IV3TojXzUtAD5+t3kFNuvzbQX91nnRxR4Lr/MyjpzqAxZFFTqVJkkuK50NS4V+eKZmgF99GNTE350AEbiMVVUDbw8L87cP527JU88cJt2F57HAj2/bhnANUaM/YwN2QWslRUUTYfGA1xYNJkwnxxvfG/0izNTlYATBaeJXy0ohIuqRm3MBWfQept+LyRoIq9zr9dH7vNdwnWYJlsjIfz5sqddmDkE7tgTHJ/4XdCPYdT1sjyAsonHtXbNick6tRxP6V6JDSOPJFWgpI4PKDg2O0zYjciyv40/wARsTxFqgO70H04S5fpfxf5udlSO2Or96YUhAoEAVwQ9iw5iCN/5ufTDaKybkAP91UcPoruFdZKFBkEbJABx7KZ/91YSbP7u0ERvhwAyOwgpXQ==
    team-message: AgCv8TrTlQeuv4Hbkkjp+EHbTGIMoo8+iC2PkecCQub+8DC3Y1tTeugcdTutBSfftJcz8ZFSKZl6xgd+mcdWcvZftcIYp1EU7yJS+6iVpPlXklQbN2az3rpbkeGWrymDIEPEqEHUKrBfKeWD6gomH9yrnaun+uP8NUNj9HBWDXIiq972uCfIPxaP/nhZ+IoRuT6ZlgcYFnSkLK2P7Tc4TvaiRBALcOfFndRbXHLx/4thr93lQ3MhKLzM/zGgigj2DTo8XQqr2dpTpNhKXb0EW4a7FylB2uFj2wsZgozmJwfhPgUlYMKMs/FmI1Vrl6dykEYcMAwIkoCza2q+d0J7IKpXyOJJv4zP3aa2VQ7P2thxwzH9oh/gQTbe2MDvnjwOl88CtrC12jHiN4u1fzmkMScQCKAhdtHb4FrmZqvQjaVZbbBI1+qZRzOMKcjJB5hU4CTL9i3cLkCAS+WIJg4ZeuYB+sK6hW5SfCPqZzfaJ5gQeeZ8vA5bjeTbtApLoUHmC70fuPCq2B5WkqvVzbGuWkw37wfubQotn43B8EIxhPDHn0DlsEEnb8h2BQPxk9bkEeA4vQKj9hMQWunQEj1tllheAtdw10DyPTDI3UD3635plRMCmLxgzvFmb1m2lEZgqhii+XeFsCGb22YYTPd4fGEVWX3OIdam4Nyr0KP6CatMP43RrAewSqaq3Uz7SQCN5+syHbSeHEj9+XURPIkI1FVW7uHAHJ8=
  template:
    metadata:
      name: demo-secret
      namespace: demo
