---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  encryptedData:
    password: AgBSIpuAqLQ0qlixpMgiVio3n5z2bQlEV13LH8gHvsddgvjhtiktUklp0Norahmb8b/ETtG2/C4/M4eGw7CBRn8BAIxceZLIgO5tXXr0y16Sj88WkjrfULxsJ5Mfx9aVRs9Omgpgw2ldPneE8smFYIRRsAjsWMp4H1zlMIIfDYLLc28G/1bPFgLp0IioLuM31q83NfFMbNX/+X2vQVLTR8hjcH4bH0A7fN0IdKnI+GTQ9lmqNfi4JXjjNCpITLRHlPgDK9PcnGg0CFBD9kTnjq+uCEJcIyQrHpkelr/cj0695E8fqz2HNxXxHkAvSRaZh5AHuDXBML11sD1WPPktweYM8jFAk6PdZzq7tXqjQ4Ui5CEnE0g8Tt7YiqqRNmj4WyEWoFCVT3HSyIAw1Pssg7qBK2mcUFrypvU/uZ3LO1LR/xtOnHWsPKaLGpXAAtGXMQyUPjALtj58KO3hheuwVH8TVTwoi1vGB0BP4o1mO1jJhYZ7fkkZyjGmxnyyAadAQU1GchEs7i+0u8Ab9pKdlsRJOI8J+ZT9HgqsRqJ/pUvBArzziPwxmPioq+CWQzROKanM5Uxha8/q0/brk7E86BGQM7JMuNAQqPDCQ6B7o3NKasTwWrirS43DCOl17HBEfeOrrSAC6VzclFTpFWlig/I5HxBLKxJxCeayRapS/ftKNnPx3gHVbk6ADpp1WkeaYcbffs4+qqocdNj3cHCxpg0M
    username: AgAnHaarzKEbuVCyHmzBqV0oeVeBpTOoGt/ZxyjD3tsRIEu+TRE4kxSfWjeaVb6BpsEN2PqjtQhjv++1JhylY3XFfuUAAJSY5PBnbAXWYEOj83S5bUegy7LvjITv7nC37iOGMgiwDUtOR4QKj9/1xMsJh2iaq6tTmmM4I4iC0ABh44zK4GpHqywQ9Sjs6w7yU1xRfIPl6RE25J2rTHtlzGe35k8ff7dmhzvhTghm72yR9RZUwat81vwwMvmrIZ00rwDHoG2ZytJDza8BYEwtGYp93+CEhChKwKqOyMTq8csGYlBMfmyLAQ2avtlGWookTw1sIDaU09c6iDqpsfLZ14nb5jGEUBTRSPhUxcQX9ursseH0w1DPpMEhUnMBW/fD1Y7CTGA19jX7Jp36iW4wODOq65poMPMKVYo5ys43WFusAVMJUdkuaHG46Je71qbRzpfAF3cGRJkBkFn+HnaROVYtGb8GCd5sEPkHZI8R2jQb7ZQzVRR+33CUDjhBDOjEcu7iQI+B85xAWvurV4Wh/yVGGzJNCHXh32yaZidk8DQZsLfCMNwbyJpY6K7uByrB3FmfuM4V3a1F+pM/a/zWWIF+tSSCrcIG9EGkbX+gpgvo4Po5yMqQ/GyfRV5njBd18fnRZm+OTODGcvJDz5LYBo3VrUTgj2IAdUP0wtgPpOtGID28SoSITrx610er/1xZyqtBixag5j0kSw==
  template:
    metadata:
      name: app-db-secret
      namespace: demo
