---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  encryptedData:
    password: AgAPGkKWRqgpkT6bPcixqfWy8L2sfkgfTjdlOWQV/XKSncyPcR/dLtD63998dycvauMXNZHbjLXBOENqXzHfBnD6aWcX165mByrvpSYXujHuXjGkHwEpVSnucvKuRCusvRFTq2QJ2GfQEqGbGmCyyAtS0/AXQ7HBYUK9sjmLED2t5wCTtIvfZpEdmwKpcb3KgJ98Hwrr83eabiuTHQ0e+unbUOcrfTDQvfns15ZsH8SmgHBQYXQtBRHgfsLetR6W2bamReLBHpr99SWdPo2TU158VOwwJYrl8F9AHANL00ZJAX0xMsJ2a9q4mE0h+H/we1mmDNc2U4cjEuD8PVsV3sh/NNe/IceRuGebWiRQ1tjHFJB+Hx0CP/lvL+tEEHEZp/AVP6AQe/G9n1kn+D5yfmDQ2fecmSUGws8kpcPy6CKLNy6opmJjcJ8UDXDvwF7uKwWgNeeqEJJpZqYF6z+yQCXPcNFTwhMvKtOHVSbLNAQqXnovQTgDE/qaQIRR0bxGv82aHAl5HKBfDVjnsygV+mtJh7jmuwc9pno9BXe1PBFRApjLDTWI8+Sbld30QV62cLN50h3MjM7j+esRDcsoc+IcsgaFfZeWrlPN2Wu2eZHM+1SQKrcGTlQ0//O0Wwi9+nrWcrjIdD3uQAXzWoahUiJAmm7KNiWcA+gMlG82Be+zzvAARgsIP+vypdJ718DLpUjhlzv04HuiLQnLw6raH3FU
    username: AgA7+zfaSKIVClHtN3jbl5nVl+dYrNIktFUirhOZVoWfwShgNb+TaWoOJ+G1KVCXN7P9szRG4GYcCeSUmN/yqg0m3xnPZkpqy0/QAO10jx3mmpC2iub8kqnhLVad94N7TXCmWJIPqQ4J6ag/donr8nApbQsFnAzklMFK46GzviRFtWHg38HphFoZfyD5kvmGYZMD9LWM+ta0HMz1oKjU0szBwzRhUmrbkRu2OSkYGneMgWsWI9F8OIS1k9u1mFYHfuDQ7kxVA7N0yHVznrey7j3oIfttZOPfjeAnQGkdkdlbVJEM1tOuiofiXr8hidxL/wf7uq7pt+PxHytjtSmPbUE3Rp/J+9d5gpWzSFZd0UQYP1ZzE3b4UBf3bRuFxUfgC5uvmQFH7dVHzdmySohvff65V6BgZMO8BnFYHFaoh1QtAh+DQb5oK5DNg03A+1eSh6212Yk77qG1alKGX90RsoBOoDgbXOtAy9AIqrEuZZTsM7hgTYInJ6SVad3rgz9umvaKOU4b6rkZfr8whRA8OlBKe5RgD4rFmPHF8XI6W79PJZwb+3968ZKYpwJzw1RYCgw0HxvrfYhVSiZhQnk0DjjoLIa/7PLxWO1+snUxMOUUO/YzfDdFxV7ufk3My3urweTWqZ4rbGhvBIKdOHlLhVn/S+VazAyXLzqpreD7n+W8fe34LdOi9gJ9dXqxi8Yc+V3n0UKXr1vY6w==
  template:
    metadata:
      name: app-db-secret
      namespace: demo
