---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  encryptedData:
    password: AgBNoz3hrKi9M+ukOwTHSop5X/2EM8pzeQs9IlDJb76oFzN0r73PUJlM19hqqoCM6OXpeDnrAy/6aChrzYZTfIuCMlkst7R98LNZ7MLjxNtKGwMEqJGC6zJ06ykHKA5BRlnXt0COqfHvIzGZDZcEInV2YVB42UNUbNI7XgMO3p1z6IoBkAurUj5NTr9cK2g2L6Uq0daL3RCXEFt/la+CKDi5Rvq+k8WL+ztrre+WRg00lEnYkD8Xmkj/fzp07q0L/AVsSwNwl5+zIlz14ejdEXpFlkz2JrrzM3JP36EACLvHHmQQ1etc19ROpsUJC1yhrq9F2N6687+W6tyf4DlsNoiCJyObbwncURo6VOeoWDuVoWR6/LmAPToxL+BR3GIKpRvwmCkVhtoQdwPGSFRUg7o0hF+67QVU/MV66Ox/EZTD5HgwhPWfocy3Tls2VuSgs0a8+yOEUvB8ovTeRr1vr5sjAl74byAyjQkCNIMaKlZm5nGQeof6sdIpZbEzg8nv0/4/uWC7OjUMO8gIXkEeg5tXjkbxc06v8zXS036ekGpsh5bmBTaaRDpQItK3XIQsOHW5xb1CfZXHsS2Oss7D4QXT7y5D7rOFsu/IkhVdFlS+3+N8DMrQvdT2G3LeJYzxUtGVEIVBmh6prwgyTanz0hKA3dGWiPmOxmfpF2GqTDYkrL9OoOXQE+V1JPPSindTQ70uLzsb/iif5bRn5H3SK7/Zkw==
    username: AgAC6H4zp8jStpew5luLLZ143iaYY0UX2deM3OtplZSUDbI+2awvnYEG/Zvkw7M7DijMO8AsW/ShxcdmSp/2cJZC/6iijbApFd1qd+MThZMdPhbFzdO/e9u9rm0Gre1CEgLe2cI1lqhsXmQ7rXati+/zFVckamgD8AcvPtaRHwNDtU1sf6dfHjQdgmbL57Sb9oHF+TMaERiLSwamckhLvGr1Ed+1R5FBj7CMxjkyyU/fAoJWzi/gGHfHN1Dw7dOKxWxqRmITf2aZndUl9A1CdcAVbqeJg6NU2pt+PgDSUgtZy8HjDtEH6zFOo3HfGb4MHzdIwkKiug1ESKvlFAgrgm5QCEWm/VdGHSGjDilgTvVftyCriHe1UVdUrsWST/5wX8xsu3ROLu2l5tjMRec/LB8AQXwzC56hbmVj28XZslpKF5JsJfJe2EDB7cflqEtUW2ZtTuhiR4a5IFA8+V1F7u+ueZ6VyslsJXJzOiInAmsKOC6QPsQsvOs07MKg/EXhOZg/V3qSrhJZhHPis974zadxfhWsN60Ik87Wd+YX8yCaQN7UkJprKdNFVXNo5tXTqzGgPfc2YVt0uoxrGENZ106FOqY2L6gUOKao/Fx4thuq/0uc08Fl2hnmdmbVBfvQoj52sRu5LlqSryJr2iTWm4bNktWz8dQ181S1itHUb9GvvlHcH7+V4Zx+BdOhizPf1U8YwWwKSqcwHA==
  template:
    metadata:
      name: app-db-secret
      namespace: demo
