resources:
- ../../base
- sealed-secret.yaml

patches:
- path: replica-patch.yaml

images:
- name: demo-app
  newName: ghcr.io/markof88/gitops-demo/demo-app
  newTag: aa33e26f4ae7fcb0b688788a2d3c92d43d21a58c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
