resources:
- ../../base
- sealed-secret.yaml

patches:
- path: replica-patch.yaml

images:
- name: demo-app
  newName: ghcr.io/markof88/gitops-demo/demo-app
  newTag: 5736249e7ed3cfec694a8dfcad3c92d8fd5d65ac
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
