resources:
- ../../base
- sealed-secret.yaml
- postgres-secret.yaml

patches:
- path: replica-patch.yaml

images:
- name: demo-app
  newName: ghcr.io/markof88/gitops-demo/demo-app
  newTag: b8c0cea394354e81145798251eaea2df2e199324
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
