---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgBIpwldGvQkONmLckUFIiydn8M0ijt+TXQJDVFRP33jO7DALMhPw5FYyTaeqwAOoMrQRxWAzWSBdy2fXNW2GP8kCrRbL15U0khkAl/8Iivaol3kGm3GBumu8sfZJCgBhzzC7rrUZLen+6trb5J1Pf5oNycL2pK61ARubXW2cdotwTN47zUNFrnNyQmVUIHUvdvcH3hmZvD5geVDJg0PRDGw2pf8pJBlkTHcvRq5Q/snGwxZ3yG76CwdteeE/f7fsWPmr3unFE0PTQ/PmsvXXl8iMUuiUvMk0FNwCiUi8WdaglXrV6uDGxUimIsM0Hp+ioKRaulR3dA2V4sMenZReCQ/JjFDIXjCJA7nWGDYSWzb0p1mxbBEDRAPgnSiULb/0XdJ/Zz1dm46jfqdgrcVKjBh93atqFKQGHb3pW7ZVpCp+o5DeqZzSK/PQmihlvXn+Ve1J+OR1FARFLWLCJtpQZpxp1R0NhuobEZWdwRItEitXPefwVbasYDJAlm6OAqkXukGYEU9haflhKV+e/fA+vqlmpIv0xnKlEBd3mPOPF12gwlvdKahmS2s2/OezY9x/bWXVDi4Fatzrbryw4xwqv2qFLlBy2O5Yd0g7O0c5AvBW+yuVNXVe6Yr+OQTQkl7O0t+6nhmo/VTHYmt0aTXg2OQihBSw53eNM00l6VKovqkDGbc9/+5dh3KrmJ8zS8HMyLqiL9mXUv53gosceFZco82AT77Yw==
    team-message: AgC5zzzQk/icG2DNIJUrEZPQQJj+N8M0AStwbRTd3pqNiVhGUZI1A6TDS9gUe645zHyl8ag9c+5mIM45wtOv4SdTAWAnet5CA7QCKSzJ8SYu5HKulMZYovYDkHnG7n/FFuONAh+VxsxIze/Lrfkw9j0nFw2zQEecQvKGzT9UFLW5gUe2yeHa7BfsCiwe1UOXc4xG0FtPZyYAACzOjszyC/mNmaf0FdF02fZWDcxlibvQLwOlbxvxPZZGb6KWVBTO+SeF1kgU9BXRQAd4ppwN+xVT/IN9UppVtxIyiezOvuTJDTDPX5PkTxgtvtqxC6q3pdiym1yaBUDXeQxhfBtl9IfTVTUOv/lh59S9Du4vlSjN3fzHYPWCgssnAJjULm0Y2W2M+4i0EF14751uctSwMFuRbtMGn0FCMz/SoFbqhHDPMBIBmQOShPTpCfbaVg876Su6tx16o9dLSbANJMEcsTy/jPhFdYz9MR/faD/zNKK9EJwKPp3Br8kPBmeDXIC2THtoZGpPH3nhSUDOo2Z8imgca3Slp65Yap4uqvotBek8BBRkEfFcmZfESjaZSbdApVPnDnPlIxdIbDKntighP42wLP5yGeo1Oa/g2CpPAQLYQF+5BFQtiGoEhVyL6OOH7pMGFXQO8j8y0ySrbozl1kjVpo2/UGjDPim9GKSHhX99j4XECKUKLGgkQPcG+0Q66zf0bCDBvYXyKFXVmD3SEps6y5+G2YE=
  template:
    metadata:
      name: demo-secret
      namespace: demo
