---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgA/J4y0xBoe7FB1C7qoF09aOy9QpsV3qG83vxNSCy/Rf0mkUoio1+dXesJDSiHWg9CukiMYadr59CXmsAqg0oo/d0V2UuTgBZATlCHtbR+xUI7trH5ywe4GeJ6umlFsUZd/dBtY/+Tutx0V79gYTdjsADG2B40O+IAIZ+e4dkexvbjL+5IZkX7ZtRpgFDQ8io3mhPVmG08o9MfMi6WMe88wKK6X5M2KWi40hswY9B4Q0awsWcLosRi/jpsvJIzL01LJW/gcZ7UhpTXuQbDi2QLkUhJi/rNYJ2GxmsxN/H1RZxxRxoYrjNepYA0nkqCgh8DDT8/+yBhc3EIWhptvt9CFyzX8JoMdJ9W9qFNyIAXUFRh7F0tMvZY5lZb3FD/zG4ZxFGU9c3nl1tw1sTUBztfQrudO9LQHufVQE6LOAblsLJMbdX/p2C/oW1KGZ0LxbMCMFgWUrDt4SkaHDwdAT7M1UL/sbB0uA3NrZyooBvz8g2PHcXHS728IoDuA74bPNS3jBvPobO3IMjh3r2Cz0xc7ITBpjdad69Fm8y+T+RgsYX+ApUUdJ6RT4f6iLA8SnK2g6htHl52itPGYXrZa9qMEOuZU7AFqBvaFOjCltkKNVgITLKkVMMfnKRGLt78gwUulMC+AckAgwab5A9gde/KuErYbmwNfsrbwRaJVe/KhsCpErBNdiAlk6TzF+ovpnNoQErARSmZJ4DMVwhf9e4bljtJke9g=
    team-message: AgCZr5GUIZHIMeRNIHO4iUbLDj5K6gm+KhTYrh+/PEQtgVJmq2fdVVYztBpJGrjYlqaZx0Dbgaj2nce+F56VaOOKpxJUQVxb5Gdo+Yp4gzDx0B5M5GiQUZnR7nJt5ouJngAORYCsRCvgnI+ybmFMNB4kbgDJYF3K9aFdhhFjSPKpqCJvCX7or2LwMoSvWVOdqEp1iH41SgUql51eSur0zxDyvkr9opd7S/SyRXwdwej1H5fvzZY6a4feqdIeXQmFmdZyRuXu0hzV/F9xmd3gaAyjku6o8UVZ0OAN0E0hw23EJxI5boT4xVfeIZT0evRvjRBj5cemgSm2B3BuUjciOw1ipuzvicaVdvl6jbMxvobIY9JYSXlBKVOYOvaGWuOjcEUhDTNw4lC7ILWbx8VQI7Zu/ZW6Rtqlksa9u8XnQGvPwI55EWV5GBGxfRI+WWmtaIE7t1KGfNw3vgBXAxY7/mrbcXoCZyhi0g9mJPZMHms/WU2f/91GGqLj1FYLtGzewdAfwiCSLOAUeGRiXJkTWMfcgWbbxtB+H2F79t/UMWcHrbn5HKYV6/7C5InFKJSMGda1njToS4Z0REAk+OtrjWCvZRhZlH8S28Wev/txcZRSGyYUUVliyJ/Y8sA4OQENNAB+edmA+dkNYxTpSmiUPafLwqnemIW3ZBG0yeYste9+LBxFkL66l7cQX6okWO7l1/2cqVtHU9hk/uEfac7jwy7e59m/hWSb
  template:
    metadata:
      name: demo-secret
      namespace: demo
