---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    message: AgCw61ju6X+PpGLcAtY0VDNN/v09ovnYfkK4aLprRIR4NA/lEkqMGG09k9hsXeY7thLrF87xIQf+lw9TYu3zViyzqvp0lNlBq2Sybq3pQdUeksWQC+l+1KAZnOy1oZW0aBUEYdyAc3chlBMrnyEtGffPt49FYSxbxEUrE5KhZAeiykG7kmhMPqvibP27UzwqBGYo/Sgn2+csl3t3Zsv6WghjKVkhZwKH1RtJ5VAyc5ikL7hL6727AivGxAn6KEauUBwg3hZzhh6c7bU7t4C7ZOGu6S+owZDirG6vSU2crdl599vzQoGGkrNHCQBlkAEeAQOksvewiOq9bSqoBvDizOnjVUYHU97p7lhwZours3polcNC3wpC92GBSWuNFX1sUxqxo8jiVTmJ0kokLHdYJHoDekBZReniBo8A0dR284vGoWTt8B+xQ/sBqie9xIk7MtNmb9bqhFx8feQeSEbqbgOe6BkwXNZQG96LrdKVetfJ3rNWo1xwLvq5iVWqyMWjHkZpL4rv0i2YR4vR5JaBRywb5tslsjr+OXwyFj0ptcF4meeLrT5yN+2f2LpHBCDWUy7tgUj3NhP/y2+tXkRWZA4CLjrI/9ddtMx63GQS/27EvODesbQA+vVKigWN9fWDft/5a94nXhLpziwHJLMZ17uAv4NdNDsA2eyVgLFJojgVxumdv2OTvGATpd5DPXje0vSygdqPC6x8+2axrh7fNjjLaw==
  template:
    metadata:
      name: demo-secret
      namespace: demo
