{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "caralegal-service.name" . }}
  labels:
    {{- include "caralegal-service.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "caralegal-service.selectorLabels" . | nindent 6 }}
{{- end }}
