apiVersion: v1
kind: Service
metadata:
  name: {{ include "caralegal-service.name" . }}
  labels:
    {{- include "caralegal-service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "caralegal-service.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
