apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: app
        image: demo-app
        ports:
        - containerPort: 80
        env:
        - name: SECRET_MESSAGE
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: message
        - name: TEAM_MESSAGE
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: team-message
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30